In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pltn

In [2]:
df=pd.DataFrame({"nome":['Peter','Bruce', "T'Challa"],
              "simbolo": ['aranha', 'morcego', 'pantera'],
              "idade": [22, pd.NaT, 25]})

In [3]:
df.dropna() #drop nao tem informacao nao atribuido

,nome,simbolo,idade
0,Peter,aranha,22
2,T'Challa,pantera,25


In [4]:
df.dropna(inplace=True) # remove a linha do bruce, pois nao tem idade atribuida

# RMSE

In [5]:
# Valores reais
reais = [100000, 150000, 200000, 250000, 300000]

# Valores previstos pelo modelo
prev = [95000, 142000, 210000, 245000, 315000]

In [6]:
diferencas = [r - p for r, p in zip(reais, prev)]

In [7]:
quadrados_das_diferencas = [d ** 2 for d in diferencas]

In [8]:
mse = np.mean(quadrados_das_diferencas)

In [9]:
mse

87800000.0

In [10]:
rmse = np.sqrt(mse)

In [11]:
rmse

9370.165420097983

In [12]:
from sklearn.metrics import mean_squared_error

In [13]:
mse = mean_squared_error(reais, prev)

In [14]:
mse

87800000.0

In [15]:
rmse = np.sqrt(mse)

In [16]:
rmse

9370.165420097983

MAPE (Mean Absolute Percentage Error) - Erro percentual absoluto médio

In [20]:
from sklearn.metrics import mean_absolute_percentage_error

In [21]:
mape_com_sklearn = mean_absolute_percentage_error(reais, prev)

In [22]:
mape_com_sklearn * 100

4.466666666666667

# Valores Faltantes

In [24]:
from sklearn.impute import SimpleImputer

In [30]:
# Dados com valores ausentes
dados = np.array([[1, 2, 3, np.nan],
                  [4, np.nan, 6, 7],
                  [8, 2, 5, 7],
                  [8, 11, 10, 10]])

In [31]:
dados

array([[ 1.,  2.,  3., nan],
       [ 4., nan,  6.,  7.],
       [ 8.,  2.,  5.,  7.],
       [ 8., 11., 10., 10.]])

In [32]:
imputador = SimpleImputer(strategy='mean')

In [33]:
dados_imputados = imputador.fit_transform(dados)

In [ ]:
dados_imputados # ele colocou a média nos valores vazios, ou seja, no primeiro caso ele colocou a média da coluna 4, que é 7+7+10/3 = 8, e no segundo caso ele colocou a média da coluna 2, que é 2+2+11/3 = 5.

array([[ 1.,  2.,  3.,  8.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  2.,  5.,  7.],
       [ 8., 11., 10., 10.]])

In [ ]:
impurtador = SimpleImputer(strategy='most_frequent') 

In [39]:
impurtador_2 = impurtador.fit_transform(dados)

In [ ]:
impurtador_2 # colocou o mais frequente, ou seja, no primeiro caso ele colocou o 7, e no segundo caso ele colocou o 2.

array([[ 1.,  2.,  3.,  7.],
       [ 4.,  2.,  6.,  7.],
       [ 8.,  2.,  5.,  7.],
       [ 8., 11., 10., 10.]])

# Identificar Outliers
(valores atipicos ou muito discrepantes. Falhou o sensor, ou comportamento anormal)
Eles podem distorcer o modelo e levar previsões fora do esperado, tomar decições erradas etc.
Pode ser ou não uma tomada de decisão do time tirar os outliers, mas identificar é importante.

In [ ]:
# IQR Divisão interquartilica. Dividimos em quartis, ou seja, em 4 partes. O primeiro quartil é o valor que separa os 25% menores dos 75% maiores. O segundo quartil é o valor que separa os 50% menores dos 50% maiores. O terceiro quartil é o valor que separa os 75% menores dos 25% maiores. O IQR é a diferença entre o terceiro quartil e o primeiro quartil. Valores que estão abaixo do primeiro quartil - 1.5 * IQR ou acima do terceiro quartil + 1.5 * IQR são considerados outliers.
# Depois obsevamos o que esta dentro do intervalo de quartil.

In [41]:
dados = np.array([1, 2, 3, 4, 5, 100])

In [42]:
dados

array([  1,   2,   3,   4,   5, 100])

In [44]:
q1 = np.percentile(dados, 25)
q3 = np.percentile(dados, 75)
iqr = q3 - q1

In [47]:
iqr

2.5

In [48]:
# Calculo do limite inferior e superior para identificar outliers
# Nos livros de estatistica adota 1,5 para identificar outliers, ou seja, valores que estão abaixo do primeiro quartil - 1.5 * IQR ou acima do terceiro quartil + 1.5 * IQR são considerados outliers.
limite_inf = q1 - 1.5 * iqr
limite_sup = q3 + 1.5 * iqr

In [ ]:
limite_inf, limite_sup # Os valores estão considerados dentro desse intervalo. O que esta fora desse intervalo é considerado outlier. O 100 é considerado outlier, pois esta acima do limite superior.

(-1.5, 8.5)

In [50]:
outliers = np.where((dados < limite_inf) | (dados > limite_sup))[0]

In [51]:
outliers

array([5], dtype=int64)

In [ ]:
dados[outliers[0]] # mostra o outlier, ou seja, o valor 100.

100

# Remoção do outlier

In [53]:
np.delete(dados, 5)

array([1, 2, 3, 4, 5])

# Normalização dos dados em uma lista

In [ ]:
# Pré processamento
# Pode ser que mesmo que não seja outliers mas sejam muito discrepantes, muitos distintos.

In [54]:
from sklearn.preprocessing import normalize

In [56]:
# Dados a serem normalizados/padronizados
dados = np.array([2, 3, 5, 6, 7, 4, 8, 7, 6, 0])

In [57]:
dados

array([2, 3, 5, 6, 7, 4, 8, 7, 6, 0])

In [58]:
# Normalização entre 0 e 1
dados_normalizados = normalize([dados], norm='max')

In [59]:
dados_normalizados

array([[0.25 , 0.375, 0.625, 0.75 , 0.875, 0.5  , 1.   , 0.875, 0.75 ,
        0.   ]])